spring.datasource.url=jdbc:postgresql://shuttle.proxy.rlwy.net:32331/railway
spring.datasource.username=postgres
spring.datasource.password=upaQYMueTnLWmBDqCxpqMGePOqahNySd
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
server.port=8080

app.cors.allowed-origin-patterns=http://localhost:3000,http://127.0.0.1:3000,https://*.vercel.app,https://*.railway.app